name: Delete branch after merge to production

on:
  pull_request:
    types:
      - closed


jobs:
  delete_branch:
    name: Delete branch after merge to production
    runs-on: ubuntu-latest
    if: github.head_ref != 'main' && github.event.pull_request.merged == true && github.base_ref == 'production'
    steps:
      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X DELETE "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}" -H "Authorization: token ${{ env.GITHUB_TOKEN }}"
