name: workflow dispatch の インプットテスト

on:
  workflow_dispatch:
    inputs:
      input1:
        description: string だよ
        required: true
        default: 'default'
      input2:
        description: boolean だよ
        required: true
        default: false
        type: boolean

jobs:
  output-var:
    runs-on: ubuntu-latest
    steps:
      - name: output var
        run: |
          echo "input1: ${{ github.event.inputs.input1 }}"
          echo "input2: ${{ github.event.inputs.input2 }}"
